#!/usr/bin/env bash
cd "$(dirname "$(realpath -- "$0")")";

# DEPLOYER_ADDRESS=%DEPLOYER_ADDRESS_ENV%
# DEPLOYER_PRIVATEKEY=%DEPLOYER_PRIVATEKEY_ENV%
# CHAIN_ID=%CHAIN_ID_ENV%

DEPLOYER_ADDRESS=0x2cA0dFa9E49E98BFe881C1fb6388518aeE0911de
DEPLOYER_PRIVATEKEY=xxxxx
CHAIN_ID=2344

sed "s|%DEPLOYER_ADDRESS%|$DEPLOYER_ADDRESS|g; s|%DEPLOYER_PRIVATEKEY%|$DEPLOYER_PRIVATEKEY|g; s|%CHAIN_ID%|$CHAIN_ID|g" deploy_parameters.sample.json > ./config/deploy_parameters.json

